### ISSUE TITLE
adjust styling and markup required to make the container and any child components use 100% of the available page height

### ISSUE THREAD

**Issue by rodnolan** [rodnolan/shirtshop-react#2]
these gaps outlined in red have to disappear

![image](https://user-images.githubusercontent.com/1766935/33095987-7e7c74a0-ced3-11e7-98b3-4c055973e33b.png)

**Comment by TantienHime** [comment]
I've been able to get the whole thing to fill up the full height. Still need some tweaking to allow for padding, but have a good formula now. The problem was a div with no classes or ids assigned in the Config.js file. Have put the nav at 10% and the shirt/center area at 80%.
