### ISSUE TITLE
apply styles to the ShirtList and ShirtListRow components to make the items appear in a grid with a scroll bar if necessary

### ISSUE THREAD

**Issue by rodnolan** [rodnolan/shirtshop-react#3]
The data is being displayed dynamically, it's just not very pretty...
Ensure that scrolling happens when we have more items than can fit on a single screen

![image](https://user-images.githubusercontent.com/1766935/33096165-0f494a30-ced4-11e7-8308-90d5c4369a3a.png)

**Comment by TantienHime** [comment]
Re-assigning to Rod Nolan for Bootstrap implementation. Let me know if you need me to take this back or need help on this.
